application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from .views import (IndexView, AuthLoginView, AuthLogoutView, RegisterView,
                    PublisherListView, PublisherCreateView, PublisherUpdateView, PublisherDeleteView,
                    AuthorListView, AuthorCreateView, AuthorUpdateView, AuthorDeleteView,
                    BookListView, BookCreateView, BookUpdateView, BookDeleteView)

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', AuthLoginView.as_view(), name='login'),
    path('logout/', AuthLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('publisher/list/', PublisherListView.as_view(), name='publisher_list'),
    path('publisher/new/', PublisherCreateView.as_view(), name='publisher_new'),
    path('publisher/detail/<int:pk>', PublisherUpdateView.as_view(), name='publisher_update'),
    path('publisher/delete/<int:pk>', PublisherDeleteView.as_view(), name='publisher_delete'),
    path('author/list/', AuthorListView.as_view(), name='author_list'),
    path('author/new/', AuthorCreateView.as_view(), name='author_new'),
    path('author/detail/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),
    path('author/delete/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('book/list/', BookListView.as_view(), name='book_list'),
    path('book/new/', BookCreateView.as_view(), name='book_new'),
    path('book/detail/<int:pk>', BookUpdateView.as_view(), name='book_update'),
    path('book/delete/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
]

core/models.py
from django.db import models


class Publisher(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    address = models.CharField(max_length=50, verbose_name='Address')
    city = models.CharField(max_length=50, verbose_name='City')
    state_province = models.CharField(max_length=30, verbose_name='State')
    country = models.CharField(max_length=50, verbose_name='Country')
    website = models.URLField(null=True, blank=True, verbose_name='Website')

    class Meta:
        ordering = ['-name']
        verbose_name = 'Publisher'
        verbose_name_plural = 'Publishers'

    def __str__(self):
        return self.name


class Author(models.Model):
    salutation = models.CharField(max_length=10, verbose_name='Salutation')
    name = models.CharField(max_length=200, verbose_name='Name')
    email = models.EmailField(max_length=100, verbose_name='E-mail')
    headshot = models.ImageField(verbose_name='Headshot', upload_to='headshots')

    class Meta:
        ordering = ['-name']
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    authors = models.ManyToManyField(Author, related_name='books', verbose_name='Authors')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE,
                                  related_name='books', verbose_name='Publisher')
    publication_date = models.DateField(verbose_name='Publication Date')

    class Meta:
        ordering = ['-publication_date']
        verbose_name = 'Book'
        verbose_name_plural = 'Books'

    def __str__(self):
        return self.title

core/forms.py
from .models import Publisher
from django import forms


class PublisherCreateForm(forms.ModelForm):

    class Meta:
        model = Publisher
        fields = ['name', 'address', 'city', 'state_province', 'country', 'website']

core/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from .models import Publisher, Author, Book
from django.http import HttpResponse, JsonResponse
from .forms import PublisherCreateForm
from django.contrib import messages
from django.core import serializers


class RegisterView(View):
    pass


class AuthLoginView(View):
    pass


class AuthLogoutView(View):
    pass


# Index view
class IndexView(View):
    def get(self, request, *args, **kwargs):
        title = 'Welcome to the Home Page '
        message = 'Explore the navigate options and choose any'
        footer = 'Learn more about this application choosing any feature'
        context = {
            'title': title,
            'message': message,
            'footer': footer
        }
        return render(request, 'index.html', context)


# Publisher views
class PublisherListView(View):

    def get(self, request, *args, **kwargs):
        queryset = Publisher.objects.all()
        name = request.GET.get('publisher')
        if name:
            queryset = queryset.filter(name__iexact=name)
        context = {
            'publishers': queryset,
            'count': queryset.count()
        }
        return render(request, 'publisher/list.html', context)


class PublisherCreateView(CreateView):
    template_name = 'publisher/create.html'
    model = Publisher
    form_class = PublisherCreateForm
    context_object_name = 'form'
    success_url = '/publisher/list'

    def form_valid(self, form):
        if self.request.method == 'POST' and self.request.is_ajax:
            instance = form.save()
            data = serializers.serialize('json', [instance, ])
            return JsonResponse({'data': data})

    def form_invalid(self, form):
        if self.request.method == 'POST' and self.request.is_ajax:
            error = 'Form is invalid. Try again'
            print(error)
            return JsonResponse({'error': error})


class PublisherUpdateView(UpdateView):
    pass


class PublisherDeleteView(DeleteView):
    pass


# Author views
class AuthorListView(View):
    def get(self, request, *args, **kwargs):
        author = request.GET.get('author')
        email = request.GET.get('email')
        queryset = Author.objects.order_by('name')
        if author:
            queryset = queryset.filter(name__iexact=author)
        if email:
            queryset = queryset.filter(email__iexact=email)

        context = {
            'authors': queryset,
            'count': queryset.count()
        }
        return render(request, 'author/list.html', context)


class AuthorCreateView(CreateView):
    pass


class AuthorUpdateView(UpdateView):
    pass


class AuthorDeleteView(DeleteView):
    pass


# Book views
class BookListView(View):

    def get(self, request, *args, **kwargs):
        queryset = Book.objects.order_by('title')
        author = request.GET.get('author')
        publisher = request.GET.get('publisher')
        if author:
            queryset = queryset.filter(authors__name__iexact=author)
        if publisher:
            queryset = queryset.filter(publisher__name__iexact=publisher)
        context = {
            'books': queryset,
            'count': queryset.count()
        }
        return render(request, 'book/list.html', context)


class BookCreateView(CreateView):
    pass


class BookUpdateView(UpdateView):
    pass


class BookDeleteView(DeleteView):
    pass

templates/author/list.html
{% extends '../base.html' %}

{% block title %} Author Title {% endblock %}

{% block content %}

    <a class="btn btn-success">New Author</a>

    <form method="GET" class="form-inline">
        <div class="form-group mb-1">
            <input type="text" name="author" class="form-control" placeholder="Name">
        </div>
        <div class="form-group mb-1">
            <input type="text" name="email" class="form-control" placeholder="Email">
        </div>
        <input type="submit" class="btn btn-success" value="Search">
    </form>

    <table class="table">
        <thead>
            <tr>
                <th scope="col"> Salutation </th>
                <th scope="col"> Name </th>
                <th scope="col"> E-mail </th>
                <th scope="col"> Actions </th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.salutation }}</td>
                    <td>{{ author.name }}</td>
                    <td>{{ author.email }}</td>
                    <td>
                        <a href="{% url 'core:author_update' author.id %}">Edit</a>
                        |
                        <a href="{% url 'core:author_delete' author.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td><strong>Total</strong></td>
                <td><strong>{{count}}</strong></td>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http=equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow&display=swap"
        rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/components.css' %}">
        <title>{% block title %} {% endblock %}</title>
    </head>

    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"> </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:publisher_list' %}">Publisher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:author_list' %}">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:book_list' %}">Book</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link">
                                    Hello, {{ request.user.username }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:logout' %}">
                                    Logout
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:register' %}"> Sign up </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:login' %}"> Sign in </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <main class="container">
                {% block content %}{% endblock %}
            </main>
            <footer class="footer">
                <p class="paragraph"> Copyright&copy; 2020 - Developed by João Victor Rocha</p>
            </footer>
        </div>
            <script type="text/javascript" src="{% static 'js/scripts.js' %}"> </script>
    </body>

</html>

templates/book/list.html
{% extends '../base.html' %}

{% block title %} Book Title {% endblock %}

{% block content %}

    <a class="btn btn-success">New Book</a>

    <form method="GET" class="form-inline">
        <div class="form-group mb-1">
            <input type="text" name="author" class="form-control" placeholder="Author name">
        </div>
        <div class="form-group mb-1">
            <input type="text" name="publisher" class="form-control" placeholder="Publisher Name">
        </div>
        <input type="submit" class="btn btn-success" value="Search">
    </form>

    <table class="table">
        <thead>
            <tr>
                <th scope="col"> Title </th>
                <th scope="col"> Authors </th>
                <th scope="col"> Publisher </th>
                <th scope="col"> Publication Date </th>
                <th scope="col"> Actions </th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>
                        {% for author in book.authors.all %}
                            {% if not forloop.last %}
                                {{ author }},
                            {% else %}
                                {{ author }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ book.publisher.name }}</td>
                    <td>{{ book.publication_date }}</td>
                    <td>
                        <a href="{% url 'core:book_update' book.id %}">Edit</a>
                        |
                        <a href="{% url 'core:book_delete' book.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td><strong>Total</strong></td>
                <td><strong>{{count}}</strong></td>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="card text-center">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                <h5 class="card-title"> Pay atention </h5>
                <p class="card-text"> {{ message }} </p>
            </div>
            <div class="card-footer">
                <p> {{ footer }} </p>
            </div>
        </div>
        <ul class="list-group">
            <li class="list-group-item"> Create, Update, List and Delete Authors </li>
            <li class="list-group-item"> Create, Update, List and Delete Publishers </li>
            <li class="list-group-item"> Create, Update, List and Delete Books </li>
            <li class="list-group-item"> Filter all lists </li>
        </ul>
    </div>
{% endblock %}

templates/publisher/create.html
{% extends '../base.html' %}

{% block title %} Create Publisher {% endblock %}


{% block content %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert" id="error">
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST" name="newPublisher" action="{% url 'core:publisher_new' %}"
    redirect-to="{% url 'core:publisher_list' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name</label>
            <input type="text" name="name" class="form-control">
        </div>
        <div class="form-group">
            <label for="{{ form.address.id_for_label }}">Address</label>
            <input type="text" name="address" class="form-control">
        </div>
        <div class="form-group">
            <label for="{{ form.city.id_for_label }}">City</label>
            <input type="text" name="city" class="form-control">
        </div>
        <div class="form-group">
            <label for="{{ form.state_province.id_for_label }}">State</label>
            <input type="text" name="state_province" class="form-control">
        </div>
        <div class="form-group">
            <label for="{{ form.country.id_for_label }}">Country</label>
            <input type="text" name="country" class="form-control">
        </div>
        <div class="form-group">
            <label for="{{ form.website.id_for_label }}">Website</label>
            <input type="text" name="website" class="form-control">
        </div>
        <input type="submit" class="btn btn-success" value="Submit"/>
        <input type="reset" class="btn btn-danger" value="Reset"/>
    </form>

{% endblock %}

templates/publisher/list.html
{% extends '../base.html' %}

{% block title %} Publisher List {% endblock %}


{% block content %}

    <a href="{% url 'core:publisher_new' %}" class="btn btn-success">New Publisher</a>

    <form method="GET" class="form-inline">
        <div class="form-group mb-1">
            <input type="text" name="publisher" class="form-control" placeholder="Publisher name">
        </div>
        <input type="submit" class="btn btn-success" value="Search">
    </form>

    <table class="table">
        <thead>
            <tr>
                <th scope="col"> Name </th>
                <th scope="col"> Address </th>
                <th scope="col"> City </th>
                <th scope="col"> State </th>
                <th scope="col"> Country </th>
                <th scope="col"> Website </th>
                <th scope="col"> Actions </th>
            </tr>
        </thead>
        <tbody>
            {% for publish in publishers %}
                <tr>
                    <td>{{ publish.name }}</td>
                    <td>{{ publish.address }}</td>
                    <td>{{ publish.city }}</td>
                    <td>{{ publish.state_province }}</td>
                    <td>{{ publish.country }}</td>
                    {% if publish.website %}
                        <td>{{ publish.website }}</td>
                    {% else %}
                        <td> - </td>
                    {% endif %}
                    <td>
                        <a href="{% url 'core:publisher_update' publish.id %}">Edit</a>
                        |
                        <a href="{% url 'core:publisher_delete' publish.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td><strong>Total</strong></td>
                <td><strong>{{count}}</strong></td>
            </tr>
        </tbody>
    </table>
{% endblock %}